### ISSUE TITLE
 how onerous it is to download data; can it be done in code?

### ISSUE THREAD

**Issue by bnord** [lsst-epo/citizen-science-notebooks#19]
What does it take to download data from Zooniverse to do analysis?

If it can be onerous to do through the Zooniverse interface, Is there a way to do it in a script or in a notebook?

**Comment by bnord** [comment]
Notes somewhere say there is a getdata function? will that work in script/notebook?

**Comment by clareh** [comment]
Ive asked Chris for input on how to make this more seamless. Will update.

**Comment by ericdrosas87** [comment]
As @clareh noted above, we are currently working with Zooniverse to automate the process of combining the original citizen science project data with the completed Zooniverse data. More to come as the discussion and design evolves.

**Comment by ericdrosas87** [comment]
If you'd like to take a stab programmatically retrieving the classifications (Zooniverse output) then here is the API documentation to do so. Just not that accordingly to Chris of Zooniverse, Zooniverse users with a role of "project owners" and "collaborators" _should_ be able to retrieve the classifications. However, due to a bug in their API only user's with the "project owner" role can fetch the classifications programmatically.

**Comment by bnord** [comment]
this seems like something we want to get more serious about for the next version of our tutorials?

**Comment by beckynevin** [comment]
We talked about this issue in our meeting today (4/6). We decided that retrieving data from Zooniverse should be part of the main Citizen_Science_Testing.ipynb notebook. We also said we should have two options to work with the output Zooniverse data - 1) Programatically retreive the data using panoptes client, 2) Write down instructions for grabbing the csv by yourself.

**Comment by beckynevin** [comment]
Branch fetch_classifications will address this question

**Comment by beckynevin** [comment]
This branch was merged in PR #39, we now have the capability to return a dataframe from zooniverse :)
