### ISSUE TITLE
Sending flipbook manifest gives error

### ISSUE THREAD

**Issue by jsv1206** [lsst-epo/citizen-science-notebooks#63]
**Describe the bug**
Error at `cit_sci_pipeline.send_image_data` in` variable_stars` branch.
I see this error after `variable_stars_package_update` is merged with `variable_stars`

**To Reproduce**
Steps to reproduce the behavior, written in imperative mood:
1. Go to 'variable_stars' branch
2. Click on 'variable_stars.ipynb'
3. Scroll down to 'last cell'

**Expected behavior**
To send flipbook

**Actual behavior**
Attached screenshots

![flipbook_manifest](https://github.com/lsst-epo/citizen-science-notebooks/assets/13951429/3e078b34-4456-47b7-976e-5dd3882b3cca)

![error](https://github.com/lsst-epo/citizen-science-notebooks/assets/13951429/d6f508cc-7405-4f35-a31b-dfdc0bf70ae0)

**Comment by ericdrosas87** [comment]
This is there error I see in the EDC logs:

```
panoptes_client.panoptes.PanoptesAPIException: Could not find project with id='21742'
```

Can you confirm @jsv1206 that the above project indeed exists?

**Comment by eatyourgreens** [comment]
I can see the project here. 
https://www.zooniverse.org/lab/21742

There’s one user with write access: `sreevani`. Is that the account that’s trying to create the new subject set?

**Comment by ericdrosas87** [comment]
Thank you for helping troubleshoot @eatyourgreens! I _think_ @jsv1206 is the one testing as she wrote up the issue, but if someone else is testing the notebook that could be the issue. I did see that the email and slug name were left in the code so that could be the case if someone else tried to run it. I was able to successfully transfer data over using the same notebook oddly.

**Comment by eatyourgreens** [comment]
My first thought was perhaps this was a user account that hasn't been added as a project collaborator. That might give a 'project not found' error.
