### ISSUE TITLE
Retrieval cell in citsci notebook is retrieving a list instead of a dataframe

### ISSUE THREAD

**Issue by beckynevin** [lsst-epo/citizen-science-notebooks#67]
**Describe the bug**
Hi @ericdrosas87 , the final cell in citsci notebook now unexpectedly returns a list instead of a dataframe. I think we're probably just missing one line `pd.DataFrame` somewhere in `cit_sci_pipeline.retrieve_data`. This is true on the main branch and also on the beckynevin/pedgagogy_check_2
**To Reproduce**
Steps to reproduce the behavior, written in imperative mood:
1. Go to the final cell of the citsci notebook (retrieve data)
2. Run it and log onto zooniverse
3. Scroll down to see the output
4. The output (df) is in list format instead of dataframe format

**Expected behavior**
Expected df to be a dataframe

**Actual behavior**
df is a list

**Screenshots**
<img width="882" alt="Screenshot 2023-09-15 at 9 45 12 AM" src="https://github.com/lsst-epo/citizen-science-notebooks/assets/26393168/98d930d6-ab61-413f-9ace-cfd16babd4bc">

**Comment by ericdrosas87** [comment]
@beckynevin I'm off work today, but wanted to respond to this: The returning of a list is intentional to keep the science packages out of the citsci PyPI package. The separation of responsibility is such that the citsci package shouldn't need to be dependent on the science packages. I thought I had modified the `Testing` notebook to accommodate for this,  but if not I can do so Monday.

**Comment by ericdrosas87** [comment]
This issue was fixed with #72 , the `Citizen_Science_Testing` notebook now takes the list and renders a Panda dataframe. 

Apologies about not giving a heads up that I made that change and that I forgot to add back that Panda code!

**Comment by beckynevin** [comment]
No worries, sounds great and thanks for doing that. I didn't realize it would be such a quick fix or I could've done it myself. I'll close this issue.
